### ISSUE TITLE
setup.py install fails because `lxml` is not found

### ISSUE THREAD

**Issue by srid** [dcramer/feedreader#1]
You cannot do an "import feedreader" (that imports xml) in setup.py is _yet_ to automatically install lxml.

  Traceback (most recent call last):
    File "setup.py", line 5, in <module>
      import feedreader
    File "/tmp/tmpsdC0iy/feedreader-0.1/feedreader/**init**.py", line 31, in <module>
      from feedreader import *
    File "/tmp/tmpsdC0iy/feedreader-0.1/feedreader/feedreader.py", line 1, in <module>
    import lxml.objectify
  ImportError: No module named lxml.objectify

.

**Comment by dcramer** [comment]
Thanks. Moving feedreader.feedreader to feedreader.parser, and it iwll now require a direct import from that path to use it.

**Comment by srid** [comment]
Thanks. If it works, then ActiveState repository will have a binary package - http://pypm.activestate.com/list-f.html#feedreader (PyPM is to be released in a week)
